export const userReports = [
  {
    id: 1,
    type: "Hazard",
    title: "Large pothole on E 161st St",
    location: "E 161st St & River Ave",
    submittedDate: "2024-01-15",
    status: "Under Review",
    urgency: "Medium",
    views: 45,
    upvotes: 12,
    lastUpdate: "2 days ago",
  },
  {
    id: 2,
    type: "Environmental",
    title: "Broken streetlight reported",
    location: "Grand Concourse & E 149th St",
    submittedDate: "2024-01-10",
    status: "Resolved",
    urgency: "Low",
    views: 28,
    upvotes: 15,
    lastUpdate: "1 week ago",
  },
  {
    id: 3,
    type: "Crime",
    title: "Vandalism in community center",
    location: "Bronx Community Center",
    submittedDate: "2024-01-08",
    status: "Pending",
    urgency: "Medium",
    views: 63,
    upvotes: 8,
    lastUpdate: "3 days ago",
  },
  {
    id: 4,
    type: "Hazard",
    title: "Loose manhole cover",
    location: "Webster Ave & E 170th St",
    submittedDate: "2024-01-05",
    status: "Resolved",
    urgency: "High",
    views: 89,
    upvotes: 24,
    lastUpdate: "2 weeks ago",
  },
];
